### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by vbaliga** [charvey23/AvInertia#2]
https://github.com/charvey23/birdmoment/blob/11c88f2a171b4667be329769df219bd9a28ecb9d/R/mathematicalfunctions.R#L5

I don't mean to rush you, but I just happened to see this line in your commit and thought I'd give you an answer. 

In the console, what you'll want to do is make use of the `usethis::use_package()` function. [Here is a link to the help page with details](https://usethis.r-lib.org/reference/use_package.html).

Keep in mind that this should be done in the console and not as part of a script. It will automatically update our `DESCRIPTION` file with a dependency. So for `pracma`, it will look like:
``` r
usethis::use_package("pracma", type = "Imports", min_version = NULL)
```
Up to you if you want to set `min_version` to be >= 2.2.9 . Once you run that, take a look at the changes to `DESCRIPTION`. Then, whenever the package is (re)built and then a user installs it, it will automatically ensure they also have `pracma` on their computer as well.

**Comment by vbaliga** [comment]
Part II of this: as you write your functions, any time you rely on a function within another package, you will need to call it out explicitly using either `::` (or occasonally `:::`, which I can explain later). For example [on this line](https://github.com/charvey23/birdmoment/blob/11c88f2a171b4667be329769df219bd9a28ecb9d/R/mathematicalfunctions.R#L86)

https://github.com/charvey23/birdmoment/blob/11c88f2a171b4667be329769df219bd9a28ecb9d/R/mathematicalfunctions.R#L86

You'd write it as:
``` r
y_vector = pracma::cross(unit_z_vector,unit_x_vector) 
```

**Comment by charvey23** [comment]
package submitted and all info incorporated. Closing the issue
