### ISSUE TITLE
2020-09-09 anatomicalmassprop.R

### ISSUE THREAD

**Issue by vbaliga** [charvey23/AvInertia#4]
Ok here's feedback on `anatomicalmassprop.R`:

- Lines 158 - 165: Unfortunately it looks like the strategy of using `\item{}` alone does not work. We get lots of warnings when trying to document and the rendered Help file does not honor your itemized list -- it all just becomes one big block of text. I just made an edit to wrap up this stuff within a `\itemize{}` block (starting on 161 and ending on 165). Can you follow suit for all other instances in which you used `\item{}`?

I'll actually need to pause here and pick this up later tonight. Posting this now so I don't lose this!

**Comment by vbaliga** [comment]
OK picking up again:

- Lines 18, 19, 158, 276, 277: I'm a little unclear on how points should be formatted. Can you specify if any of these should be supplied as a vector, list, or matrix with special format?

I think that's it for this file!

**Comment by charvey23** [comment]
updated!
